import { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: "cat_1",
    name: "Electronics",
    products: [],
  },
  {
    id: "cat_2",
    name: "Books",
    products: [],
  },
  {
    id: "cat_3",
    name: "Clothing",
    products: [],
  },
];

export const exampleProducts: Product[] = [
  // ---------- Electronics ----------
  {
    id: "prod_1",
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    description: "High-quality wireless headphones with noise cancellation.",
    price: 129.99,
    stock: 50,
    imageUrl: ["https://images.unsplash.com/photo-1657223143985-1e06ecb9c506"],
    categoryId: "cat_1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[0],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
  {
    id: "prod_3",
    name: "4K Ultra HD Monitor",
    slug: "4k-ultra-hd-monitor",
    description:
      "Crystal-clear 27-inch 4K monitor for productivity and gaming.",
    price: 349.99,
    stock: 25,
    imageUrl: ["https://images.unsplash.com/photo-1551645120-d70bfe84c826"],
    categoryId: "cat_1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[0],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
  {
    id: "prod_4",
    name: "Mechanical Keyboard",
    slug: "mechanical-keyboard",
    description:
      "RGB mechanical keyboard with blue switches and ergonomic design.",
    price: 89.99,
    stock: 40,
    imageUrl: ["https://images.unsplash.com/photo-1587202372775-98927d6a2c54"],
    categoryId: "cat_1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[0],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
  {
    id: "prod_5",
    name: "Smartwatch Series 7",
    slug: "smartwatch-series-7",
    description: "Track your fitness and notifications with this sleek smartwatch.",
    price: 249.99,
    stock: 30,
    imageUrl: ["https://images.unsplash.com/photo-1603791452906-bb9cf34c9e7a"],
    categoryId: "cat_1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[0],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },

  // ---------- Books ----------
  {
    id: "prod_2",
    name: "Learning TypeScript",
    slug: "learning-typescript",
    description: "A beginner-friendly book to learn TypeScript step by step.",
    price: 39.99,
    stock: 100,
    imageUrl: ["https://images.unsplash.com/photo-1565229284535-2cbbe3049123"],
    categoryId: "cat_2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[1],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
  {
    id: "prod_6",
    name: "Clean Code",
    slug: "clean-code",
    description:
      "A handbook of agile software craftsmanship — a must-read for developers.",
    price: 44.99,
    stock: 80,
    imageUrl: ["https://images.unsplash.com/photo-1512820790803-83ca734da794"],
    categoryId: "cat_2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[1],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
  {
    id: "prod_7",
    name: "The Pragmatic Programmer",
    slug: "the-pragmatic-programmer",
    description:
      "Classic software engineering guide filled with practical wisdom.",
    price: 42.5,
    stock: 60,
    imageUrl: ["https://images.unsplash.com/photo-1581090700227-1e37b190418e"],
    categoryId: "cat_2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[1],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },

  // ---------- Clothing ----------
  {
    id: "prod_8",
    name: "Classic White T-Shirt",
    slug: "classic-white-tshirt",
    description: "Soft cotton white t-shirt with a comfortable fit.",
    price: 19.99,
    stock: 120,
    imageUrl: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246"],
    categoryId: "cat_3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[2],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
  {
    id: "prod_9",
    name: "Denim Jacket",
    slug: "denim-jacket",
    description:
      "Stylish blue denim jacket perfect for everyday wear.",
    price: 59.99,
    stock: 45,
    imageUrl: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f"],
    categoryId: "cat_3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[2],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
  {
    id: "prod_10",
    name: "Running Sneakers",
    slug: "running-sneakers",
    description: "Lightweight and breathable sneakers for all-day comfort.",
    price: 89.99,
    stock: 70,
    imageUrl: ["https://images.unsplash.com/photo-1519741497674-611481863552"],
    categoryId: "cat_3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: categories[2],
    cartItems: [],
    orderItems: [],
    wishlistItems: [],
  },
];
